---

- name: geerlingguy.homebrew

- src: https://github.com/bmacauley/ansible-role-dotfiles
  version: master
  name: ansible-role-dotfiles

- src: https://github.com/bmacauley/ansible-role-sublimetext
  version: master
  name: ansible-role-sublimetext

- name: geerlingguy.mas
