---
- name: Clone Vundle repository
  git:
    repo: "{{ vundle_repo }}"
    dest: "~/.vim_runtime"
    accept_hostkey: "{{ vundle_repo_accept_hostkey }}"
  become: no

- name: Install Vim modules
  command: sh ~/.vim_runtime/install_awesome_vimrc.sh
